# -*- coding: utf-8 -*-
"""Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vsANmljtPHhElyS9gOHo1cTsmBkpa9LE
"""

import pandas as pd

s = pd.Series([10,20,30,40,50])
s

s.dtype

s.values

s.index

print(s.name)

s.name = "calories"

s

# Indexing

s[0]

s[0:2] #start(included) : stop (excluded): step value (values to jump)

s[2:4]

# iloc -> location based indexing

s.iloc[3]

s.iloc[[1,3,4]]

index = ["apple", "banana", "grapes", "orange", "strawberry"]

s.index = index
s

s['grapes']

s.iloc[3]

#loc -> label based indexing.
s.loc[['grapes', 'apple']]

# In label based indexing your start as well as stop value both are included in the output.
s['banana':'orange']

fruit_protein = {
    "Avocado": 2.0,       # grams of protein
    "Guava": 2.6,
    "Blackberries": 2.0,
    "Oranges": 0.9,
    "Banana": 1.1,
    "Apples": 0.3,
    "Kiwi": 1.1,
    "Pomegranate": 1.7,
    "Mango": 0.8,
    "Cherries": 1.0
}

s2 = pd.Series(fruit_protein, name = "Protein")
s2

# Conditional Selection:

s2[s2>1]

# Logical Operators: and, or, not

s2[(s2>0.5) | (s2 <= 2)]

# not operation:

s2[~(s2>1)]

# Modyfying the series:

s2["Mango"] = 2.8

s2

import numpy as np

ser = pd.Series(['a', np.nan, 1, np.nan, 2])
s.notnull().sum()

# DataFrame:

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Alice"],
    "Age": [25, 30, 35, np.nan, 29, 25],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "HR"],
    "Salary": [50000, 60000, 70000, 62000, np.nan, 50000]
}

data

df = pd.DataFrame(data)
df

df.head(2)

df.tail(3)

# loc and iloc

df.iloc[1:3, :2] #rows, columns

df.loc[1:2, ["Age","Department"]]

df[["Age", "Department"]]

df.drop("Age", axis = 1)

df

df.shape

df.info()

df.describe()

# Broadcasting

df["Salary"] = df["Salary"] + 5000

df["Salary"]

# Renaming cokumns:

df.rename(columns = {"Department": "Dept"}, inplace = True)

df

df["Dept"].unique()

df["Dept"].value_counts()

df["Promoted Salary"] = df["Salary"] * 10

df

# Data Cleaning

df.isnull().sum()

df.dropna(how = "any") # any row that had any null value

df.dropna(how = "all") #if all the values in any row are null then we drop that row

df

df["Age"].fillna(df["Age"].mean())

df["Salary"].fillna(df["Salary"].median())

df["Age"].fillna(method = "ffill")

df["Age"].fillna(method = "bfill")

df["Name"] = df["Name"].replace("Charlie", "Rose")

df

# Duplicates:

df_dup = df[df.duplicated(keep = "last")]
df_dup

df = df.drop_duplicates()

df

# invalid values:
# Lambda -> python

df["Promoted Salary"] = df["Promoted Salary"].apply(lambda x: x/10 if x > 650000 else x)

df

name = "alice_fernandes"
df[["first_name", "last_name"]] = df["name"].str.split("_")

# apply and lambda
def multiplying_age(x):
  return x*2

df["Age"] = df["Age"].apply(multiplying_age)

df

df["Age"] = df["Age"].apply(lambda x: x/2)

df

# Joins and Merges

department_info = {
    "Dept": ["HR", "IT", "Finance"],
    "Location": ["New York", "San Francisco", "Chicago"],
    "Manager": ["Laura", "Steve", "Nina"]
}

df2 = pd.DataFrame(department_info)
df2

# Concat

pd.concat([df, df2])

pd.concat([df, df2], axis = 1)

pd.merge(df, df2, on = "Dept")



"""Importing File"""

data = pd.read_csv("data.csv")

data.head()

data.shape

data.info()

data['date'] = pd.to_datetime(data['date'])

data.info()

